name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir public
          cp -r frontend/* public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v2
